version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name saisyukadaiapplication --s3-location s3://556391696321saisyukadai/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
